move dev dependencies to dependency-groups and typecheck to separate job

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -4,37 +4,24 @@ on:
   - pull_request
 jobs:
   build:
-    runs-on: ${{ matrix.os }}
+    name: run-tests (${{ matrix.os || 'linux' }}-${{ matrix.python-version }})
+    runs-on: ${{ matrix.os || 'ubuntu' }}-latest
     strategy:
       fail-fast: false
       matrix:
         include:
-          - name: linux-3.14-typecheck
-            python-version: "3.14"
-            os: ubuntu-latest
-          - name: linux-3.13
-            python-version: "3.13"
-            os: ubuntu-latest
-          - name: linux-3.12
-            python-version: "3.12"
-            os: ubuntu-latest
-          - name: linux-3.11
-            python-version: "3.11"
-            os: ubuntu-latest
-          - name: linux-3.10
-            python-version: "3.10"
-            os: ubuntu-latest
-          - name: linux-pypy-3.11
-            python-version: pypy-3.11
-            os: ubuntu-latest
-          - name: linux-pypy-3.10
-            python-version: pypy-3.10
-            os: ubuntu-latest
+          - python-version: "3.14"
+          - python-version: "3.13"
+          - python-version: "3.12"
+          - python-version: "3.11"
+          - python-version: "3.10"
+          - python-version: pypy-3.11
+          - python-version: pypy-3.10
     steps:
-      - name: Checkout repo
+      - name: Checkout source repo
         uses: actions/checkout@v4
-      - name: Apt install system dependencies (linux unless -skip-exe)
-        if: ${{ startsWith(matrix.name, 'linux-') && !contains(matrix.name, '-skip-exe') }}
+      - name: Apt install system dependencies (linux)
+        if: ${{ matrix.os == 'ubuntu' || !matrix.os }}
         run: |
           echo "::group::Run sudo apt-get update"
           sudo apt-get update
@@ -47,23 +34,14 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
-      - name: Pip install dependencies
+      - name: Pip install . --group test
         run: |
           echo "::group::Run python -m pip install --upgrade pip setuptools wheel"
           python -m pip install --upgrade pip setuptools wheel
           echo "::endgroup::"
-          echo "::group::Run pip install .[test] mypy"
-          pip install .[test] mypy
+          echo "::group::Run pip install . --group test"
+          pip install . --group test
           echo "::endgroup::"
-      - name: Run mypy (if -typecheck)
-        if: ${{ contains(matrix.name, '-typecheck') }}
-        run: |
-          echo "::group::Run mypy"
-          FAILED=0
-          python -m mypy || FAILED=$?
-          echo "::endgroup::"
-          [ $FAILED -eq 0 ] || echo "::warning::mypy failed with exit code $FAILED"
-        shell: bash
       - name: Run clean-example.py, make-example.py and paginate-example.py
         run: |
           coverage run clean-example.py
@@ -78,5 +56,27 @@ jobs:
       - name: Upload artifacts ${{ matrix.name }}
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ matrix.name }}
+          name: ${{ matrix.os || 'linux' }}-${{ matrix.python-version }}
           path: example/_output/*.pdf
+  typecheck-code:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - python-version: "3.14"
+    steps:
+      - name: Checkout source repo
+        uses: actions/checkout@v4
+      - name: Setup Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Pip install --group typing
+        run: pip install --group typing
+      - name: Run mypy
+        if: ${{ contains(matrix.name, '-typecheck') }}
+        run: |
+          FAILED=0
+          python -m mypy || FAILED=$?
+          [ $FAILED -eq 0 ] || echo "::warning::mypy failed with exit code $FAILED"
+        shell: bash
